name: Release

jobs:
  prepare_release:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: true

  publish_labPbr_1024x:
    name: Publish LabPbr-1024x
    runs-on: ubuntu-latest
    needs: [prepare_release]
    env:
      release_filename: Chronos-LabPbr-1024x-v${{ github.run_number }}.zip
    steps:
      - uses: actions/checkout@v2
      - name: Compile LabPbr-1024x
        uses: null511/PixelGraph.GitHubAction@main
        with:
          profile: src/LabPbr-1024x.pack.yml
          zip: ${{ env.release_filename }}
      - name: Release LabPbr-1024x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.release_filename }}
          asset_name: ${{ env.release_filename }}
          asset_content_type: application/zip

  publish_labPbr_512x:
    name: Publish LabPbr-512x
    runs-on: ubuntu-latest
    needs: [prepare_release]
    env:
      release_filename: Chronos-LabPbr-512x-v${{ github.run_number }}.zip
    steps:
      - uses: actions/checkout@v2
      - name: Compile LabPbr-512x
        uses: null511/PixelGraph.GitHubAction@main
        with:
          profile: src/LabPbr-512x.pack.yml
          zip: ${{ env.release_filename }}
      - name: Release LabPbr-512x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.release_filename }}
          asset_name: ${{ env.release_filename }}
          asset_content_type: application/zip
